development:
  adapter: postgresql
  database: todos_development
  host: localhost

test: &test
  adapter: postgresql
  database: todos_test
  host: localhost

#production:
  #heroku handles production db magically

cucumber:
  <<: *test
